# -*- coding: utf-8 -*-
"""Untitled

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1vNzk-Z1JZ5NXAwlfCzUbRgY3Ls0msomf
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from matplotlib.backends.backend_pdf import PdfPages
import seaborn as sns

dataset=pd.read_csv("/content/drive/My Drive/DS_DATESET.csv")
dataset.head()

pdf=PdfPages('vizual-output.pdf')

#2-a) no. of students applied to different technologies
a=dataset['Areas of interest'].value_counts().plot(x='No of students',y='Different Technologies',figsize=(20,10),fontsize=15,color='Blue',kind='barh')
a.set_xlabel('No of students',fontsize=25)
a.set_ylabel("Different Technologies",fontsize=25)
plt.title('No of students applied to different technologies',fontsize=25)
pdf.savefig()

#2-b) The number of students applied for Data Science who knew ‘’Python” and who didn’t.
b = dataset[['Areas of interest','Programming Language Known other than Java (one major)']]
bi = b.groupby(['Areas of interest'])
bii = bi.get_group('Data Science ')
lst = list(bii['Programming Language Known other than Java (one major)'])
x=lst
lst1=[]
for i in range(0,len(lst)):
    if (x[i]=="Python"):
        lst1.append("YES")
    else:
        lst1.append("NO")
lst2 = pd.DataFrame({"Python":lst1})
be=lst2['Python'].value_counts().plot(figsize=(20,10),fontsize=15,color='pink',kind='bar')
be.set_ylabel('No. of Students in Data Science Who Know Python',fontsize=25)
be.set_xlabel("Students who know Python",fontsize=25)
plt.title('Students in Data Science Who Know Python',fontsize=25)
pdf.savefig()

#2-c) The different ways students learned about this program
c=dataset['How Did You Hear About This Internship?'].value_counts().plot(figsize=(20,10),fontsize=15,color='purple',kind='bar')
c.set_xlabel('No of students',fontsize=25)
c.set_ylabel("Different Ways",fontsize=25)
plt.title('The different ways students learned about this program',fontsize=25)
pdf.savefig()

#2-d) Students who are in the fourth year and have a CGPA greater than 8.0.
d = dataset[['Which-year are you studying in?','CGPA/ percentage']]
di = d.groupby(['Which-year are you studying in?'])
dii = di.get_group('Fourth-year')
lst = list(dii['CGPA/ percentage'])
x=lst
lst1=[]
for i in range(0,len(lst)):
    if (x[i]>8.0):
        lst1.append("Fourth Year")

lst2 = pd.DataFrame({"Fourth Year":lst1})
de=lst2['Fourth Year'].value_counts().plot(figsize=(20,10),fontsize=15,color='brown',kind='bar')
de.set_ylabel('No. of Students ',fontsize=25)
de.set_xlabel("Students who have CGPA>8.0",fontsize=25)
plt.title('Students who are in the fourth year and have a CGPA greater than 8.0.',fontsize=25)
pdf.savefig()

#2-e) Students who applied for Digital Marketing with verbal and written communication score greater than 8.
e = dataset[['Areas of interest','Rate your written communication skills [1-10]','Rate your verbal communication skills [1-10]']]
ei = e.groupby(['Areas of interest'])
eii = ei.get_group('Digital Marketing ')
lst0 = list(eii['Rate your written communication skills [1-10]'])
lst = list(eii['Rate your verbal communication skills [1-10]'])
x=lst0
y=lst
lst1=[]
for i in range(0,624):
        if x[i]>8.0:
            if y[i]>8.0:
                lst1.append("Rating>8.0")
          
lst2 = pd.DataFrame({"Digital Marketing":lst1})
e0 = lst2['Digital Marketing'].value_counts().plot(kind="barh",figsize=(20,10),color='orange',fontsize=15)
plt.title("Stduents in Digital Marketing with Verbal and Written Score greater than 8", fontsize = 20)
e0.set_xlabel('Number of Students',fontsize = 15)
e0.set_ylabel('Verbal and Written Rating',fontsize = 15)
pdf.savefig()

#2-f) Year-wise and area of study wise classification of students
plt.figure(figsize=(20,10))
sns.countplot(x ='Which-year are you studying in?', hue = "Major/Area of Study", data = dataset)
plt.title("Year-wise and area of study wise classification of students",fontsize=15)
pdf.savefig()

#2-g) City and college wise classification of students.
plt.figure(figsize=(20,10))
sns.countplot(y='College name', hue = "City", data = dataset)
plt.title("City and college wise classification of students",fontsize=15)
pdf.savefig()

#2-h) Plot the relationship between the CGPA and the target variable.
plt.figure(figsize=(20,10))
plt.scatter(dataset['Label'],dataset['CGPA/ percentage'],color='red')
plt.ylabel('CGPA',fontsize=25)
plt.xlabel('Target Variable',fontsize=25)
plt.title('Relationship between the CGPA and the target variable',fontsize=25)
pdf.savefig()

#2-i) Plot the relationship between the Area of Interest and the target variable.
plt.figure(figsize=(20,10))
plt.scatter(dataset['Label'],dataset['Areas of interest'],color='blue',marker='.')
plt.ylabel('Areas of interest',fontsize=25)
plt.xlabel('Target Variable',fontsize=25)
plt.title('Relationship between the Area of Interest and the target variable',fontsize=25)
pdf.savefig()

#2-j) Plot the relationship between the year of study, major, and the target variable.
plt.figure(figsize=(20,10))
sns.scatterplot(dataset['Which-year are you studying in?'],dataset['Major/Area of Study'],hue='Label',data=dataset,x_jitter=True,y_jitter=True)
plt.ylabel('Area of study',fontsize=25)
plt.xlabel('Year of study',fontsize=25)
plt.title('Relationship between the Area of Interest and the target variable',fontsize=25)
pdf.savefig()

pdf.close()